import os
import yaml
from pathlib import Path
from correction_model_workflow.data_preparation import HDF5Writer

# first, save data to h5 format

# step 1 - load the data 
molecules_data_folder = os.getenv('MOLECULES_DATA_PATH')
if molecules_data_folder is None:
    raise ValueError("Please set the path for the molecule data path with MOLECULES_DATA_PATH environment variable. Data must be generated by SPARC DFT library")

# start the workflow from saving data to h5 
# but get the system type first

def process_data_into_h5(molecules_data_folder):
    config_path = Path(__file__).parent / 'config.yml'
    # load config
    with open(config_path, 'r') as config_file:
        config = yaml.safe_load(config_file)
    
    system_type = config['system_type']
    
    # Initialize HDF5Writer with the loaded system_type
    hdf5_writer = HDF5Writer(molecules_data_folder, system_type)

if __name__ == "__main__":
    process_data_into_h5(molecules_data_folder)
    
    # TODO turn path setting from main function in save to hdf5 into class function, for now this has been passed to the config file

    # TODO: 
    # system_type = "molecules_new"
    # if not os.path.exists(f"./hdf5_molecules_latest_data/{system_type}"):
    #     os.makedirs(f"./hdf5_molecules_latest_data/{system_type}")
    









