import os
from correction_model_workflow.data_preparation import HDF5Writer

# first, save data to h5 format

# step 1 - load the data 
molecules_data_folder = os.getenv('MOLECULES_DATA_PATH')
if molecules_data_folder is None:
    raise ValueError("Please set the path for the molecule data path with MOLECULES_DATA_PATH environment variable. Data must be generated by SPARC DFT library")


# start the workflow from saving h5 
hdf5_writer = HDF5Writer()

def process_data_into_h5







