import os
import yaml
import glob
from pathlib import Path
from correction_model_workflow.discard_vacuum import DiscardVacuum
from correction_model_workflow.data_preparation import HDF5Writer
from correction_model_workflow.system_subsample import SystemSubsampler
from correction_model_workflow.partitioning_scheme import Partitioner
from correction_model_workflow.overall_subsample import OverallSubsampler
from correction_model_workflow.training import EnergyCorrectionFitter


# start the workflow from saving data to h5 
# but get the system type first
def process_data_into_h5(config):
    molecules_data_folder = config['molecules_path']
    
    if molecules_data_folder == "/path/to/molecules/data":
        raise ValueError("Please set the path for the molecule data path with molecules_path field in config.yml. NOTE: Data must be generated by SPARC DFT library")

    system_type = config['system_type']
    mcsh_max_order = config['mcsh_max_order']
    mcsh_max_r = config['mcsh_max_r']
    functional = config.get('functional', None)

    # match the hdf5 class directory structure
    output_dir = f"./hdf5_molecules_latest_data/{system_type}"
    os.makedirs(output_dir, exist_ok=True)

    systems = os.listdir(molecules_data_folder)

    # process each system
    for system in systems:
        hdf5_writer = HDF5Writer(molecules_data_folder, system_type, system, functional)
        hdf5_writer.process_system(mcsh_max_order, mcsh_max_r)

# discover h5 files after processing
def get_h5_files(mcsh_max_order, mcsh_max_r, system_type):
    output_dir = f"./hdf5_molecules_latest_data/{system_type}"
    h5_pattern = os.path.join(output_dir, f"*_HSMP_*l_{mcsh_max_order}_rcut_{mcsh_max_r:.6f}.h5")
    return glob.glob(h5_pattern)

# data is now processed into h5, discard vacuum environments
def discard_vacuum(h5_output_path, config):
    processor = DiscardVacuum(
        mcsh_max_order=config['mcsh_max_order'],
        mcsh_step_size=config['mcsh_step_size'],
        mcsh_max_r=config['mcsh_max_r']
    )
    
    # Get all HDF5 files in the output directory
    h5_files = get_h5_files(h5_output_path, config['mcsh_max_order'], config['mcsh_max_r'])
    
    if not h5_files:
        print("No HDF5 files found to process!")
        return
    
    # Process each file
    for h5_path in h5_files:
        print(f"Processing vacuum removal for: {os.path.basename(h5_path)}")
        processor.process_system(h5_path)

# run sub-sampling process
def run_subsampling(config):
    """    
    Args:
        config (dict)
    """
    # Get base directory from config
    base_dir = f"./hdf5_molecules_latest_data/{config['system_type']}"
    
    # Get all HDF5 files in the output directory
    h5_files = get_h5_files(config['mcsh_max_order'], config['mcsh_max_r'], config['system_type'])
    
    if not h5_files:
        print("No HDF5 files found to process!")
        return
    
    # Process each file
    for h5_path in h5_files:
        print(f"Processing subsampling for: {os.path.basename(h5_path)}")
        
        # Initialize and run subsampling
        processor = Subsampling(
            system_type=config['system_type'],
            system_path=h5_path,
            cutoff_sig=config['cutoff_sig'],
            no_vac_discard=config.get('no_vac_discard', True),  # Default to True if not specified
            std_scale=config.get('std_scale', False)  # Default to False if not specified
        )
        processor.process()

def run_overall_subsampling(config):
    """    
    Args:
        config (dict): Configuration dictionary containing parameters
    """
    print("Starting overall subsampling process...")
    
    # Initialize overall subsampler
    overall_subsampler = OverallSubsampler(
        overall_cutoff_sig=config['overall_cutoff_sig'],
        system_cutoff_sig=config['cutoff_sig'],  # Using the same cutoff from system subsampling
        std_scale=config.get('overall_std_scale', True),
        base_dir=config.get('base_dir', "./")  # Get base directory from config or use default
    )
    
    try:
        # Run the overall subsampling process
        subsampled_data, elapsed_time = overall_subsampler.process()
        print(f"Overall subsampling completed in {elapsed_time:.2f} seconds")
        print(f"Final number of samples: {len(subsampled_data)}")
    except Exception as e:
        print(f"Error during overall subsampling: {str(e)}")
        raise

# run partitioning scheme 
def run_partitioning(config):
    output_dir = f"partitioned_data/{config['system_type']}"
    os.makedirs(output_dir, exist_ok=True)
    
    # Get all H5 files
    h5_files = get_h5_files(config['mcsh_max_order'], config['mcsh_max_r'], config['system_type'])
    
    if not h5_files:
        print("No HDF5 files found for partitioning!")
        return
        
    # Initialize partitioner
    partitioner = Partitioner(config)
    
    # Run partitioning
    refdata_path = config['reference_data_path']
    if not os.path.exists(refdata_path):
        raise ValueError(f"Reference data not found at: {refdata_path}")
        
    partitioner.run_partitioning(h5_files, refdata_path, output_dir)
    print(f"Partitioning complete. Results saved to: {output_dir}")

# run model training 
def run_model_training(config):
    """
    EnergyCorrectionFitter
    Args:
        config (dict): Configuration dictionary containing training parameters
    """
    print("Starting model training process...")
    
    try:
        trainer = EnergyCorrectionFitter(
            mcsh=config['mcsh_max_order'],
            rcut=config['mcsh_max_r'],
            overall_sig=config['overall_cutoff_sig'],
            cutoff_sig=config['cutoff_sig'],
            ccsdt_file=config['ccsdt_energy_file'],
            pbe_file=config['pbe_energy_file'],
            atomic_number_file=config['atomic_number_file'],
            count_path=config['count_path'],
            stdscale=config.get('std_scale', False)
        )
        
        # Run the main training process
        trainer.main(
            config['mcsh_max_order'],
            config['mcsh_max_r'],
            config['overall_cutoff_sig'],
            config['cutoff_sig'],
            config['ccsdt_energy_file'],
            config['pbe_energy_file'],
            config['atomic_number_file'],
            config['count_path']
        )
        
        print("Model training completed successfully!")
        
    except Exception as e:
        print(f"Error during model training: {str(e)}")
        raise

# perform validation
# NOTE: validation jupyter notebook examples for unseen molecules are under validation folder

if __name__ == "__main__":
    
    # TODO: currently config file is read in other functions 
    # want to read it from the main function instead
    config_path = Path(__file__).parent / 'config.yml'

    # load molecules
    # NOTE: only molecules must be used for training, since you are testing the predictive power on unseen systems

    # load config
    with open(config_path, 'r') as config_file:
        config = yaml.safe_load(config_file)

    process_data_into_h5(config)

    discard_vacuum(config)

    run_subsampling() # per system

    run_overall_subsampling(config)

    run_partitioning(config)

    run_model_training(config)

    # now validation steps - see jupyter notebooks

    # TODO turn path setting from main function in save to hdf5 into class function, for now this has been passed to the config file











